### ISSUE TITLE
System.MissingMethodException: Method not found

### ISSUE THREAD

**Issue by perdub** [Xwilarg/BooruSharp#47] opened 2022-08-29 19:53 UTC
I try use pixiv api: i can succesful login, but when i try call `GetRandomPostAsync()` i get System.MissingMethodException: Method not found

Stacktrace:
Unhandled exception. System.MissingMethodException: Method not found: 'Void BooruSharp.Search.Post.SearchResult..ctor(System.Uri, System.Uri, System.Uri, BooruSharp.Search.Post.Rating, System.Collections.Generic.IList1<System.String>, Int32, System.Nullable1<Int32>, Int32, Int32, System.Nullable1<Int32>, System.Nullable1<Int32>, System.Nullable1<System.DateTime>, System.String, System.Nullable1<Int32>, System.String)'.
   at BooruSharp.Others.Pixiv.ParseSearchResult(JToken post)
   at BooruSharp.Others.Pixiv.GetRandomPostAsync(String[] tagsArg)

**Comment by Xwilarg** [comment] 2022-08-29 19:54
I'll have a look, however please note that you must give at least one tag for Pixiv GetRandomPostAsync to work

**Comment by perdub** [comment] 2022-08-29 19:58
> I'll have a look, however please note that you must give at least one tag for Pixiv GetRandomPostAsync to work

Tags are specified, other api classes perfectly work

**Comment by Xwilarg** [comment] 2022-08-29 20:06
Would you mind showing me your code?

**Comment by perdub** [comment] 2022-08-29 20:26
public async Task<Picture> GetImage(List<string> banned, params string[] tags)
{
            var q = await api.GetRandomPostAsync(tags);
            while (((int)q.Rating) > ((int)localtarget) || (q.Tags!=null?CheckTags(banned, q.Tags.ToList()):false) || (q.FileUrl!=null?isVideo(q.FileUrl.AbsoluteUri):true) || q.FileUrl==null)
            {
                 q = await api.GetRandomPostAsync(tags);
            }
            return new Picture(q.FileUrl.AbsoluteUri,q);
}

In a while loop i check if SearchResult corresponds something conditions

**Comment by Xwilarg** [comment] 2022-08-29 21:24
Did you install BooruSharp.Others using NuGet?

**Comment by perdub** [comment] 2022-08-29 21:39
> Did you install BooruSharp.Others using NuGet?

Yes, BooruSharp(3.5.4) and BooruSharp.Others(2.2.0) installed from nuget.

**Comment by Rasmus715** [comment] 2022-09-05 07:19
Can confirm. Copypasting code from Readme gives me the same error.  

Error: 
Unhandled exception. System.MissingMethodException: Method not found: 'Void BooruSharp.Search.Post.SearchResult..ctor(System.Uri, System.Uri, System.Uri, BooruSharp.Search.Post.Rating, System.Collections.Generic.IList`1<System.String>, Int32, System.Nullable`1<Int32>, Int32, Int32, System.Nullable`1<Int32>, System.Nullable`1<Int32>, System.Nullable`1<System.DateTime>, System.String, System.Nullable`1<Int32>, System.String)'.

Code: 
var booru = new BooruSharp.Others.Pixiv();
await booru.LoginAsync(configuration.GetSection("PIXIV_REFRESH_TOKEN").Value);
var post = await booru.GetRandomPostAsync("シンボリルドルフ(ウマ娘)");

Same as the person above got both BooruSharp and BooruSharp.Others packages installed

**Comment by Xwilarg** [comment] 2022-09-05 12:33
Sorry for my lack of answer, it took me a bit of time because I'm quite busy these days but I'm planning to work on it this week

**Comment by Xwilarg** [comment] 2022-09-05 13:17
Uhm weirdly enough I can't manage to reproduce the issue
![image](https://user-images.githubusercontent.com/20053454/188458685-3b128b3c-72a4-4fe5-a886-3595e7b469d3.png)

**Comment by perdub** [comment] 2022-09-05 13:21
I solved problem with little change pixiv class code, [fork](https://github.com/lesh6295-png/BooruSharp/tree/master)

Its not a good solution, but Its work for me

**Comment by Xwilarg** [comment] 2022-09-05 13:43
Having a closer look at your changes, I noticed the issue was that your BooruSharp version was too recent

I uploaded a new version of BooruSharp.Others to NuGet to solve this issue: https://www.nuget.org/packages/BooruSharp.Others/2.2.1

**Comment by perdub** [comment] 2022-09-05 14:46
> Having a closer look at your changes, I noticed the issue was that your BooruSharp version was too recent
> 
> I uploaded a new version of BooruSharp.Others to NuGet to solve this issue: https://www.nuget.org/packages/BooruSharp.Others/2.2.1

Yes, now Pixiv api working, but `SearchResult.FileUrl` on request return 403. When we add `Referer` header with `https://www.pixiv.net/` value to request, its work perfectly. I think it would be nice if you add this trip with header to https://github.com/Xwilarg/BooruSharp/#pixiv for those who want download image

**Comment by Xwilarg** [comment] 2022-09-05 15:03
You can use ImageToByteArrayAsync to get the content of an image given a SearchResult

**Comment by Xwilarg** [comment] 2022-09-06 17:31
I'm gonna close this issue if it's solved, feel free to open it back if needed

**Closed as completed by Xwilarg** 2022-09-06 17:31 UTC
Labels: bug
